/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nitro V
 */
public class LeaseAssignmentUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LeaseAssignmentUI.class.getName());

    /**
     * Creates new form LeaseAssignmentUI
     */
    public LeaseAssignmentUI() {
        initComponents();
        populateRenterDropdown(); // Fills the renter dropdown on window startup
        populateUnitDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbRenter = new javax.swing.JComboBox<>();
        cmbUnit = new javax.swing.JComboBox();
        btnIssueLease = new javax.swing.JButton();
        txtStartDate = new javax.swing.JTextField();
        txtEndDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Select Renter Account:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Select Rental Unit:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Start Date (YYYY-MM-DD):");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("End Date (YYYY-MM-DD):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        cmbRenter.setBackground(new java.awt.Color(0, 51, 51));
        cmbRenter.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        cmbRenter.setForeground(new java.awt.Color(255, 255, 255));
        cmbRenter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbRenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 180, -1));

        cmbUnit.setBackground(new java.awt.Color(0, 51, 51));
        cmbUnit.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        cmbUnit.setForeground(new java.awt.Color(255, 255, 255));
        cmbUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUnitActionPerformed(evt);
            }
        });
        getContentPane().add(cmbUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 176, 180, 40));

        btnIssueLease.setBackground(new java.awt.Color(7, 24, 24));
        btnIssueLease.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        btnIssueLease.setForeground(new java.awt.Color(255, 255, 255));
        btnIssueLease.setText("Issue Lease Contract");
        btnIssueLease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueLeaseActionPerformed(evt);
            }
        });
        getContentPane().add(btnIssueLease, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, 30));

        txtStartDate.setEditable(false);
        txtStartDate.setBackground(new java.awt.Color(0, 51, 51));
        txtStartDate.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        txtStartDate.setForeground(new java.awt.Color(255, 255, 255));
        txtStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 170, 40));

        txtEndDate.setBackground(new java.awt.Color(0, 51, 51));
        txtEndDate.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        txtEndDate.setForeground(new java.awt.Color(255, 255, 255));
        txtEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 170, 40));

        jLabel6.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("LEASE CONTRACTS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 50));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 490, 10));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 490, 10));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 10, 500));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 10, 500));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BLACK BACKGROUND.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIssueLeaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueLeaseActionPerformed
        // TODO add your handling code here:
        String renterSelection = (String) cmbRenter.getSelectedItem();
String unitSelection = (String) cmbUnit.getSelectedItem();
String startDate = txtStartDate.getText().trim();
String endDate = txtEndDate.getText().trim();

if (renterSelection == null || unitSelection == null || startDate.isEmpty() || endDate.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please complete all lease criteria fields.");
    return;
}

// Extract the ID number from our formatted dropdown text (splits at the first space)
int renterId = Integer.parseInt(renterSelection.split(" ")[0]);
int unitId = Integer.parseInt(unitSelection.split(" ")[0]);

// SQL query to save into the Lease table (Table 3)
String sql = "INSERT INTO Lease (renter_id, unit_id, start_date, end_date) VALUES (?, ?, ?, ?)";

try (java.sql.Connection conn = DBConnection.getConnection();
     java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
    
    pstmt.setInt(1, renterId);
    pstmt.setInt(2, unitId);
    pstmt.setString(3, startDate); // Matches YYYY-MM-DD database layout format
    pstmt.setString(4, endDate);
    
    pstmt.executeUpdate();
    javax.swing.JOptionPane.showMessageDialog(this, "Lease agreement issued successfully!");
    
    txtStartDate.setText("");
    txtEndDate.setText("");
} catch (Exception ex) {
    // Triggers an error alert if the room or renter is already occupied (due to our UNIQUE constraints!)
    javax.swing.JOptionPane.showMessageDialog(this, "Lease Assignment Failed: That renter or unit already has an active lease!");
}
    }
private void populateUnitDropdown() {
        cmbUnit.removeAllItems(); 
        
        String sql = "SELECT unit_id, unit_number FROM RentalUnit"; 
        
        try (java.sql.Connection conn = DBConnection.getConnection();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
             java.sql.ResultSet rs = pstmt.executeQuery()) {
            
            while (rs.next()) {
                int id = rs.getInt("unit_id");
                String unitNum = rs.getString("unit_number");
                
                cmbUnit.addItem(new UnitItem(id, unitNum));
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading units: " + ex.getMessage());
        }
        } // End of your previous code

    class UnitItem { 
        private int id;
        private String unitNumber;

        public UnitItem(int id, String unitNumber) {
            this.id = id;
            this.unitNumber = unitNumber;
        }

        public int getId() {
            return id;
        }

        @Override
        public String toString() {
            return unitNumber; 
        }
    
        
    }//GEN-LAST:event_btnIssueLeaseActionPerformed

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed

    private void txtEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndDateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MainMenuUI().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUnitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LeaseAssignmentUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIssueLease;
    private javax.swing.JComboBox<String> cmbRenter;
    private javax.swing.JComboBox cmbUnit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables
// 1. Reads registered renter profiles and loads them into your account picker
private void populateRenterDropdown() {
    cmbRenter.removeAllItems();
    String sql = "SELECT renter_id, username FROM Renter";
    try (java.sql.Connection conn = DBConnection.getConnection();
         java.sql.Statement stmt = conn.createStatement();
         java.sql.ResultSet rs = stmt.executeQuery(sql)) {
        
        while (rs.next()) {
            // Displays "1 - johndoe"
            cmbRenter.addItem(rs.getInt("renter_id") + " - " + rs.getString("username"));
        }
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading renters: " + ex.getMessage());
    }
}


}
