/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nitro V
 */
public class RenterPaymentUI extends javax.swing.JFrame {
    private int loggedInRenterId = -1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RenterPaymentUI.class.getName());

    /**
     * Creates new form RenterPaymentUI
     */
    public RenterPaymentUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtLoginUser = new javax.swing.JTextField();
        txtLoginPass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAmountPaid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbMethod = new javax.swing.JComboBox<>();
        btnSubmitPayment = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        btnLogin.setBackground(new java.awt.Color(7, 24, 24));
        btnLogin.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 180, 40));

        txtLoginUser.setBackground(new java.awt.Color(0, 51, 51));
        txtLoginUser.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        txtLoginUser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtLoginUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 200, 40));

        txtLoginPass.setBackground(new java.awt.Color(0, 51, 51));
        txtLoginPass.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        txtLoginPass.setForeground(new java.awt.Color(255, 255, 255));
        txtLoginPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtLoginPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 200, 40));

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Amount to Pay:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        txtAmountPaid.setBackground(new java.awt.Color(0, 51, 51));
        txtAmountPaid.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        txtAmountPaid.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtAmountPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 200, 40));

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Payment Method:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        cmbMethod.setBackground(new java.awt.Color(0, 51, 51));
        cmbMethod.setEditable(true);
        cmbMethod.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        cmbMethod.setForeground(new java.awt.Color(255, 255, 255));
        cmbMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gcash", "Cash", "Bank Transfer" }));
        getContentPane().add(cmbMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 200, 40));

        btnSubmitPayment.setBackground(new java.awt.Color(7, 24, 24));
        btnSubmitPayment.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        btnSubmitPayment.setText("Submit Payment Log");
        btnSubmitPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmitPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 410, 180, 45));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("RENTER PAYMENT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 490, 10));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 490, 10));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, 500));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 10, 500));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BLACK BACKGROUND.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginPassActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String user = txtLoginUser.getText().trim();
String pass = txtLoginPass.getText().trim();

if (user.isEmpty() || pass.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please enter your username and password.");
    return;
}

String sql = "SELECT renter_id, first_name FROM Renter WHERE username = ? AND password = ?";

try (java.sql.Connection conn = DBConnection.getConnection();
     java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
    
    pstmt.setString(1, user);
    pstmt.setString(2, pass);
    
    java.sql.ResultSet rs = pstmt.executeQuery();
    if (rs.next()) {
        loggedInRenterId = rs.getInt("renter_id"); // Store their ID in our tracking variable
        String name = rs.getString("first_name");
        
        javax.swing.JOptionPane.showMessageDialog(this, "Welcome back, " + name + "! You can now log your payment below.");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid credentials. Please try again.");
    }
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Login Error: " + ex.getMessage());
}
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSubmitPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPaymentActionPerformed
        // TODO add your handling code here
        // 1. Guard rail check: Ensure they logged in first!
if (loggedInRenterId == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please log in at the top before submitting a payment.");
    return;
}

String amountStr = txtAmountPaid.getText().trim();
String method = (String) cmbMethod.getSelectedItem();

if (amountStr.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please enter the amount you paid.");
    return;
}

// SQL query to log data directly into the Payment table (Table 4)
String sql = "INSERT INTO Payment (renter_id, amount_paid, payment_date, payment_method) VALUES (?, ?, CURDATE(), ?)";

try (java.sql.Connection conn = DBConnection.getConnection();
     java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
    
    pstmt.setInt(1, loggedInRenterId);
    pstmt.setDouble(2, Double.parseDouble(amountStr));
    pstmt.setString(3, method);
    
    pstmt.executeUpdate();
    javax.swing.JOptionPane.showMessageDialog(this, "Payment logged successfully! The landlord will verify it shortly.");
    
    txtAmountPaid.setText(""); // Clear the input field
} catch (NumberFormatException nfe) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number for the amount paid.");
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error logging payment: " + ex.getMessage());
}
    }//GEN-LAST:event_btnSubmitPaymentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MainMenuUI().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RenterPaymentUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSubmitPayment;
    private javax.swing.JComboBox<String> cmbMethod;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtAmountPaid;
    private javax.swing.JTextField txtLoginPass;
    private javax.swing.JTextField txtLoginUser;
    // End of variables declaration//GEN-END:variables
}
