/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nitro V
 */
public class UnitRenterManagerUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UnitRenterManagerUI.class.getName());

    /**
     * Creates new form UnitRenterManagerUI
     */
    public UnitRenterManagerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUnitNumber = new javax.swing.JTextField();
        txtUnitType = new javax.swing.JTextField();
        txtMonthlyRent = new javax.swing.JTextField();
        btnSaveRenter = new javax.swing.JButton();
        btnSaveUnit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 110, 30));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, 30));

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("First Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 20));

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Last Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Phone:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        txtUsername.setBackground(new java.awt.Color(0, 51, 51));
        txtUsername.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 180, 40));

        txtPassword.setBackground(new java.awt.Color(0, 51, 51));
        txtPassword.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 180, 40));

        txtFirstName.setBackground(new java.awt.Color(0, 51, 51));
        txtFirstName.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 180, 40));

        txtLastName.setBackground(new java.awt.Color(0, 51, 51));
        txtLastName.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 180, 40));

        txtPhone.setBackground(new java.awt.Color(0, 51, 51));
        txtPhone.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 180, 40));

        jLabel6.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Unit Number:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Unit Type:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 110, 20));

        jLabel8.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Monthly Rent:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        txtUnitNumber.setBackground(new java.awt.Color(0, 51, 51));
        txtUnitNumber.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtUnitNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtUnitNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 140, 40));

        txtUnitType.setBackground(new java.awt.Color(0, 51, 51));
        txtUnitType.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        txtUnitType.setForeground(new java.awt.Color(255, 255, 255));
        txtUnitType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitTypeActionPerformed(evt);
            }
        });
        getContentPane().add(txtUnitType, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 140, 40));

        txtMonthlyRent.setBackground(new java.awt.Color(0, 51, 51));
        txtMonthlyRent.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        txtMonthlyRent.setForeground(new java.awt.Color(255, 255, 255));
        txtMonthlyRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonthlyRentActionPerformed(evt);
            }
        });
        getContentPane().add(txtMonthlyRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 266, 140, 40));

        btnSaveRenter.setBackground(new java.awt.Color(7, 24, 24));
        btnSaveRenter.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        btnSaveRenter.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveRenter.setText("Add Renter Account");
        btnSaveRenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRenterActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveRenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 180, 40));

        btnSaveUnit.setBackground(new java.awt.Color(7, 24, 24));
        btnSaveUnit.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        btnSaveUnit.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveUnit.setText("Add Rental Unit");
        btnSaveUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUnitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, -1, 40));

        jLabel10.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("RENTERS AND UNITS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 370, 10));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 10, 520));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 370, 10));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 10, 530));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, 370, 10));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 370, 10));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 370, 10));

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 10, 530));

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 10, 530));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BLACK BACKGROUND.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 670));

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 10, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMonthlyRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonthlyRentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonthlyRentActionPerformed

    private void txtUnitNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitNumberActionPerformed

    private void btnSaveRenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRenterActionPerformed
        // TODO add your handling code here:
        String user = txtUsername.getText().trim();
String pass = txtPassword.getText().trim();
String fName = txtFirstName.getText().trim();
String lName = txtLastName.getText().trim();
String phone = txtPhone.getText().trim();

// Check if mandatory fields are empty
if(user.isEmpty() || pass.isEmpty() || fName.isEmpty() || lName.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all Renter fields.");
    return;
}

// SQL query to insert into our Renter table (Table 1)
String sql = "INSERT INTO Renter (username, password, first_name, last_name, phone) VALUES (?, ?, ?, ?, ?)";

try (java.sql.Connection conn = DBConnection.getConnection();
     java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
    
    pstmt.setString(1, user);
    pstmt.setString(2, pass);
    pstmt.setString(3, fName);
    pstmt.setString(4, lName);
    pstmt.setString(5, phone);
    
    pstmt.executeUpdate();
    javax.swing.JOptionPane.showMessageDialog(this, "Renter account registered successfully!");
    
    // Clear fields
    txtUsername.setText(""); txtPassword.setText(""); 
    txtFirstName.setText(""); txtLastName.setText(""); txtPhone.setText("");
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
}
    }//GEN-LAST:event_btnSaveRenterActionPerformed

    private void btnSaveUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUnitActionPerformed
        // TODO add your handling code here:
        String unitNum = txtUnitNumber.getText().trim();
String unitType = txtUnitType.getText().trim();
String rentStr = txtMonthlyRent.getText().trim();

// Check if mandatory fields are empty
if(unitNum.isEmpty() || rentStr.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please enter both Unit Number and Monthly Rent.");
    return;
}

// SQL query to insert into our RentalUnit table (Table 2)
String sql = "INSERT INTO RentalUnit (unit_number, unit_type, monthly_rent) VALUES (?, ?, ?)";

try (java.sql.Connection conn = DBConnection.getConnection();
     java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
    
    pstmt.setString(1, unitNum);
    pstmt.setString(2, unitType);
    pstmt.setDouble(3, Double.parseDouble(rentStr)); // Converts text to decimal number
    
    pstmt.executeUpdate();
    javax.swing.JOptionPane.showMessageDialog(this, "Rental Unit added to inventory!");
    
    // Clear fields
    txtUnitNumber.setText(""); txtUnitType.setText(""); txtMonthlyRent.setText("");
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error adding unit: " + ex.getMessage());
}
    }//GEN-LAST:event_btnSaveUnitActionPerformed

    private void txtUnitTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MainMenuUI().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UnitRenterManagerUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveRenter;
    private javax.swing.JButton btnSaveUnit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMonthlyRent;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUnitNumber;
    private javax.swing.JTextField txtUnitType;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
